# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b69684fb44f44e793f1be2fa126b044ff9f9be5df7fc6fac8ae8e9e04d1eced96c68a662b640559e3493ac8a4633c9699e2e734f1ad3f89b969128c78a7bcf99

test:
  secret_key_base: 858a0014763de9f588d3a5056d812286aaa882c4a9bf0b97e83530f16c5d2392dc164db6a1959226e9680300d660bdf5ef174bd56edb13c8d0830e77d208fbb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
